name: "Dan Leech"
author: "Dan Leech"
description: "I design software, tinker with type, climb mountains and brew coffee."
url: http://danleech.com
permalink: /blog/:Y/:M/:D/:title/index.html
markdown: redcarpet