name: "Dan Leech"
url: http://danleech.com
author: "Dan Leech"
image: /images/avatar-large.jpg
description: "Systems Designer in Bath, UK"
permalink: /articles/:title/
post_dirs: false
sass:
    sass_dir: _sass
    style: compressed