name: "Dan Leech"
author: "Dan Leech"
description: "I design software, tinker with type, climb mountains and brew coffee."
keywords: "danleech, dan leech, daniel leech, d_leech, leechio, simple icons"
url: http://danleech.com
image: /images/og.png
permalink: /articles/:title/
post_dirs: false
markdown: redcarpet
sass:
    style: compressed